### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ikarth** [Syomus/ProceduralToolkit#3]
One thing that might help people who want to use the toolkit is if you explicitly include an open-source license, such as the MIT license. That way, most of the legal questions people might have are already covered, and people will hopefully feel more confident about submitting code to be included.
(If you haven't checked it out before http://choosealicense.com/ is useful.)

**Comment by BasmanovDaniil** [comment]
Good point, updated readme. Are you feeling more confident to contribute? :smile:
