### ISSUE TITLE
In the terrain example.. Terrain Mesh?

### ISSUE THREAD

**Issue by enriqif** [Syomus/ProceduralToolkit#51]
where is located the terrain Mesh in the terrain example

**Comment by BasmanovDaniil** [comment]
In memory or in the scene. When the mesh is generated it is not saved
anywhere, if you want to have it as a file, you can use the context menu on
it's mesh filter, it will be saved as an asset file in the native to Unity
format.

пт, 31 авг. 2018 г., 23:05 Enrique Flores <notifications@github.com>:
