### ISSUE TITLE
MeshPrimitives methods Sphere and FlatSphere use the wrong parameters

### ISSUE THREAD

**Issue by Hotrian** [Syomus/ProceduralToolkit#6]
I noticed MeshPrimitives.Sphere and MeshPrimitives.FlatSphere use the longitudeSegments parameter twice and ignore the latitudeSegments parameter. I assume this isn't the intended usage.

**Comment by Hotrian** [comment]
Also 'height' is spelt 'heignt' on Prism and Cylinder

**Comment by Hotrian** [comment]
Pyramid also.. Great toolkit though, no complaints.

**Comment by BasmanovDaniil** [comment]
Good find, thank you. Mesh primitives are next on my list for refactoring.
