### ISSUE TITLE
ConfiguratorBase Couldnt not be found and AssignDraftToMeshFilter does not exist in the current context

### ISSUE THREAD

**Issue by Terradice** [Syomus/ProceduralToolkit#60]
They arent working! I tried the low poly terrain scene but i just get the ConfiguratorBase couldnt be found error, i tried to comment out all the code that uses configuratorbase but now theres no AssignDraftToMeshFilter, please help

**Comment by BasmanovDaniil** [comment]
Which version are you using? Do you have `Assets\ProceduralToolkit\Examples\Common` folder? It seems to me that your installation is incorrect, delete `ProceduralToolkit` folder and then reinstall the toolkit, it should help.

**Comment by Terradice** [comment]
Thank you so much, that was the problem
