### ISSUE TITLE
How to make water waves with transparency

### ISSUE THREAD

**Issue by nathanRamaNoodles** [Syomus/ProceduralToolkit#61]
I've seen in some other projects, for example, [Equilinox](https://youtu.be/K6qqQACUxXI), where the water is moving in realtime.  I was wondering if that's possible with this library.  It would be nice to see the waves move and the transparency would be a nice touch.

Thanks,
Nathan^2

**Comment by igniuss** [comment]
Personally think that would be far easier and cheaper with just plane and a vertex shader 🤷‍♂️
