### ISSUE TITLE
Please release v0.2.3

### ISSUE THREAD

**Issue by favoyang** [Syomus/ProceduralToolkit#63]
Hi @Syomus,

Thanks for creating the amazing project. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 77 packages as of December 2019,

I've added [ProceduralToolkit ](https://openupm.com/packages/com.syomus.proceduraltoolkit/) to the platform, however since the package.json was newly added this year, not included in any GitHub releases (git tags) yet, the service can not generate a working bundle. **Would you please create a new release *v.0.2.3*?** The build pipeline will notice it and generate a bundle in a short time. (3-10mins).

If this looks interesting for you, you can consider adding [the badge](https://openupm.com/docs/adding-badge.html) to README. Here's an example project https://github.com/favoyang/unity-addressable-importer

BR
Favo

**Comment by BasmanovDaniil** [comment]
Intriguing, I will take a look.

**Comment by favoyang** [comment]
@BasmanovDaniil any updates on creating GitHub release?

BTW, to learn best practices of maintaining an upm repository, please checkout https://openupm.com/docs/managing-upm-project.html (the second article maybe interesting for automating the process process)

**Comment by BasmanovDaniil** [comment]
Done

**Comment by favoyang** [comment]
Awesome, it works (0.2.3) https://openupm.com/packages/com.syomus.proceduraltoolkit/
