### ISSUE TITLE
Is it possible to create buildings in-editor? (Outside of runtime)

### ISSUE THREAD

**Issue by randoomx8** [Syomus/ProceduralToolkit#65]
Iv read the readme and checked for other similar questions before posting this; nobody seems to have asked this before, which means that im missing something obvious here, sorry for being a dumbass.

How can I make the buildings in-editor? Not being able to _**see**_ the buildings inside of the editor is a bit of a problem, since I tend to guess distances poorly.
I tried making a prefab out of the building generator in the "buildings" scene, but that certainly did not work since it was lacking the Left Panel and Platform reference.

After, I tried using the "Building Generator Component (Script)" which is used in the scene named the same. This was an improvement since it worked, but I could not figure out how to make it generate while in-editor, nor how to edit the parameters to make different types of buildings (besides the floor amount and roof type).

Sorry for the stupid question, I just cant seem to figure this out.

**Comment by BasmanovDaniil** [comment]
Hello! The building generator is fairly basic and isn't really meant as an editor tool, it is just an example. I've commited an editor script for BuildingGeneratorComponent that should allow you to generate buildings at editor time, but don't expect much :)
![image](https://user-images.githubusercontent.com/451590/78533044-ec632b80-77f0-11ea-9ab4-6f97df99735e.png)
https://github.com/Syomus/ProceduralToolkit/blob/f5c213b1ecbc6e6e6a73f96daf4c58cfec99f703/Samples~/Buildings/Editor/BuildingGeneratorComponentEditor.cs#L1-L28

**Comment by randoomx8** [comment]
Im using the asset store version of the toolkit and this script gives me several errors.
Should I use a different version?
![image](https://user-images.githubusercontent.com/15611064/78807345-3819fe80-79c4-11ea-97c1-7bb976143897.png)

**Comment by BasmanovDaniil** [comment]
Ah, the asset store version is older. It would be best if you install the latest version via the Package Manager. See [README.md](https://github.com/Syomus/ProceduralToolkit/blob/master/README.md) for details.

**Comment by randoomx8** [comment]
Will do
