### ISSUE TITLE
Is there a way to add new set of samples

### ISSUE THREAD

**Issue by dusho** [Syomus/ProceduralToolkit#66]
Have been playing a bit with toolkit, but when importing fork into Packages, samples folder is not shown in Unity (because of ~ in name?), so not sure how to contribute with some new ones.
I do use newest Unity 2020 beta, but I don't think that is an issue here. I'm sure I imported something in wrong way or doing something wrong as I'm not able to see C# code from Packages in VS - no C# project. Expected to have things in same locations in order to create pull requests..

**Comment by BasmanovDaniil** [comment]
Hello! Sorry for the late reply.
After some investigation, it seems that there is still no hassle-free way to work with Samples~ folder. Package manager team sure works fast. Anyway, renamed and commited the samples folder without  the tilde, should be visible in editor now.
