### ISSUE TITLE
Knapsack with floating point capacity uses only small items

### ISSUE THREAD

**Issue by Swahhillie** [Syomus/ProceduralToolkit#72]
### Description
The knapsack algorithm breaks if it can't fill the whole bag. 
It will fill the entire bag with the smallest weight item instead.
### Version
* Unity: 2019.4.35f
* ProceduralToolkit:  0.2.3
### Steps to reproduce

```
public void TestKnapsack()
{
    var set = new Dictionary<int, float>()
    {
        { 1, 1f }, { 2, 2f }, { 4, 4f }
    };
    
    string Result(Dictionary<int, int> result)
    {
        var str = "";
        foreach (var p in result)
        {
            str += $"{p.Key} * {p.Value}\n";
        }

        return str;
    }

    var ten = PTUtils.Knapsack(set, 10.0f);
    var tenPointFive = PTUtils.Knapsack(set, 10.5f);
    
    //as expected
    Debug.Log(Result(ten));
    //4 * 2
    //2 * 1
    //1 * 0
    
    //wrong
    Debug.Log(Result(tenPointFive));
    //4 * 0
    //2 * 0
    //1 * 10
}
```
Run the provided code and see that the result is not as expected.

**Comment by BasmanovDaniil** [comment]
Nice catch, thanks, I will take a look!

**Comment by BasmanovDaniil** [comment]
@Swahhillie, I've changed the behaviour to be more consistent with expectations, you can see the new version here:
https://github.com/Syomus/ProceduralToolkit/blob/48c93f9eb1a629947408d9060fd5175eb5304737/Runtime/PTUtils.cs#L61-L159
