### ISSUE TITLE
MeshDraft Mesh Constructor

### ISSUE THREAD

**Issue by iDevelopThings** [Syomus/ProceduralToolkit#75]
Hey, first of all, thanks for the great toolkit!

I was looking around and I cannot find much information on this;

I was playing with the building generator, and was curious if I would be able to essentially use predefined meshes(models), from looking at the code it looks like it's possible to create a new instance of MeshDraft with the supplied mesh, but then I get these two errors:
![image](https://user-images.githubusercontent.com/4105581/218015508-62f1255a-0593-47d3-a32f-d41968323130.png)

Mainly I'm trying to figure out if I can use a combo of custom building "segments"(made in Blender for ex) and the Polygon assets to construct buildings. I really like the system you made, it will work great for the problem I'm trying to solve... if I can figure out this one issue :D 

To test it, I just replaced the calls to ProceduralFacadeElement.Wall with this: 
![image](https://user-images.githubusercontent.com/4105581/218016805-5bd80e36-f311-4da0-a80b-732756447b44.png)

Is this supported or am I just missing something simple? 

Thanks

**Comment by BasmanovDaniil** [comment]
Hello @iDevelopThings! The issue's most likely cause is that you are trying to combine procedural and hand-made segments in a single mesh. Procedural segments do not have uvs or tangents, while it seems like yours do have them. When meshes with and without uvs are combined, Unity outputs the errors like the ones you are seeing.

There are several solutions to this issue:
1. Remove all uvs and tangents. You can do it either in the source meshes or in the combined mesh draft right before it is converted to mesh. This will normalize available channels across all meshes, but you will lose your uv-mapping, obviously.
2. Use a separate mesh and renderer for uv-mapped segments like it is done for roofs. You will need to juggle two collections of segments in your code, but you will be able to have both hand-made uvs and procedural segments.
3. Add uv/tangent channels to procedural segments. They can either be filled with zeros, or you can code actual uv-maps for all segments. That will also resolve the conflict between channels.
